listen              1935;
max_connections     1000;
srs_log_tank        console;

http_server {
    enabled         on;
    listen          8080;
    dir             /data;
}

vhost __defaultVhost__ {
    hls {
        enabled             on;
        hls_fragment        6;
        hls_window          30;
        hls_wait_keyframe   on;
        hls_path            /data/hls;
        hls_m3u8_file       [app]/[stream].m3u8;
        hls_ts_file         [app]/[stream]-[seq].ts;
    }
}

