package com.thlam.streaming.common.enums;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum ApiResponseCode {

    USER_REGISTERED("USER_REGISTERED"),
    LOGIN_SUCCESS("LOGIN_SUCCESS"),
    USER_PROFILE("USER_PROFILE"),
    PROFILE_UPDATED("PROFILE_UPDATED"),
    PASSWORD_UPDATED("PASSWORD_UPDATED"),
    ROLES_RETRIEVED("ROLES_RETRIEVED"),
    PERMISSIONS_RETRIEVED("PERMISSIONS_RETRIEVED"),
    USER_ROLES_RETRIEVED("USER_ROLES_RETRIEVED"),
    USER_ROLE_ASSIGNED("USER_ROLE_ASSIGNED"),
    USER_ROLE_REMOVED("USER_ROLE_REMOVED"),
    STREAM_CREATED("STREAM_CREATED"),
    STREAMS_RETRIEVED("STREAMS_RETRIEVED"),
    STREAM_RETRIEVED("STREAM_RETRIEVED"),
    STREAM_UPDATED("STREAM_UPDATED"),
    STREAM_CANCELLED("STREAM_CANCELLED"),
    STREAM_CREDENTIALS_ROTATED("STREAM_CREDENTIALS_ROTATED"),
    STREAM_PLAYBACK("STREAM_PLAYBACK"),
    STREAM_VIEW_STARTED("STREAM_VIEW_STARTED"),
    STREAM_VIEW_UPDATED("STREAM_VIEW_UPDATED"),
    STREAM_FOLLOW_UPDATED("STREAM_FOLLOW_UPDATED"),
    STREAM_LIKE_UPDATED("STREAM_LIKE_UPDATED"),
    STREAM_STATISTICS("STREAM_STATISTICS");

    private final String code;
}
